name = "throwforward-stack-durable-objects"
compatibility_date = "2024-05-28"
main = "./dist/_worker.js"

[[durable_objects.bindings]]
name = "RATE_LIMITER"
class_name = "RateLimiter"

[[migrations]]
tag = "v1"
new_classes = ["RateLimiter"]
